accordion + button + page
js-tasks-ru/htmlcss-20230227_msdm83 pull request #3
Opened 2023-03-13 02:31 UTC by msdm83

2023-03-13 02:31 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-03-15 00:43 UTC, GSemikozov requested changes

2023-03-15 00:43 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +  padding: 3rem 4rem;
темы по адаптивной верстке еще не было, но никто не запрещает сразу использовать относительные единицы измерения) однако - неужели у кнопки паддинг будет сверху-снизу 24, а слева-справа - 32? (слева-справа на самом деле можно и такой паддинг, просто по вертикальным видимо неправильно было посчитано))

2023-03-15 00:43 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +  cursor: default;
лучше pointer-events: none

2023-03-15 00:43 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.button--primary {
можно и такой вариант модификаторов использовать, не буду против. Но тогда в дальнейшем надо будет придерживаться этого подхода. Но я бы рекомендовал использовать тот вариант, который предложен в доке по БЭМ )

2023-03-15 00:43 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +[open] .accordion__summary:after {
не просто open безотносительно любого элемента, но - .accordion[open]

2023-03-15 00:43 UTC, GSemikozov commented on 03-lection1/02-accordion/index.html
> +<details class="accordion">
на самом деле верстаем не 3 отдельных аккордиона, а один - то с тремя элементами (раскрывающимися секциями). Можно завернуть все секции в общий div с классом блока, а элементы переименовать например в .accordion__item (и кстати тогда и марджин снизу можно будет проставить)

2023-03-15 00:43 UTC, GSemikozov commented on components/page/page.css
> +.page__header {
лучше все-таки выделить отдельно header, footer, main

2023-03-24 15:48 UTC, msdm83 commented on 03-lection1/01-button/button.css
> +.button--primary {
оставлю модификаторы через --. в этом случае легче читать 
block__item-name--modifier чем block__iten-name-modifier

2023-03-24 15:49 UTC, msdm83 commented on 03-lection1/02-accordion/accordion.css
> +[open] .accordion__summary:after {
fixed

2023-03-29 09:10 UTC, GSemikozov requested changes

2023-03-29 09:10 UTC, GSemikozov commented on 03-lection1/02-accordion/index.html
> +  <details class="accordion-item">
accordion__item

2023-03-29 18:39 UTC, msdm83 commented on 03-lection1/02-accordion/index.html
> +  <details class="accordion-item">
fixed

2023-03-29 18:43 UTC, msdm83 commented on components/page/page.css
> +.page__header {
хочу оставит так и посмотреть какие проблемы это может породить. по сути сейчас страница выглядит как блок с елементами типа head/footer/etc. С одной стороны можно бы вынести если бы шапка выглядела как то сложнее, с другой стороны в блоке "страница" она нужна именно для позиционирования а не для стилизации контрола который будет внутри контейнера для шапки.

2023-03-29 18:44 UTC, msdm83 commented on 03-lection1/02-accordion/index.html
> +<details class="accordion">
fixed

2023-03-29 18:45 UTC, msdm83 commented on 03-lection1/01-button/button.css
> +  padding: 3rem 4rem;
fixed

2023-03-30 10:46 UTC, GSemikozov approved these changes

2023-03-30 10:46 UTC, merged